version: 0.0.0.{build}

environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"

install:
  - cmd: "%PYTHON%\\python.exe -m pip install"

build: off

test_script:
  - "%PYTHON%\\python.exe setup.py test"
